### ISSUE TITLE
Send ETag with request and check for 304 in return

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-registry#10]

**Comment by stevenvegt** [comment]
Currently github codeload does not seem to support the `If-None-Match` request header. If supplied the same content and status 200 gets returned.

**Comment by woutslakhorst** [comment]
what about `If-Modified-Since`

**Comment by stevenvegt** [comment]
There is no `Last-Modified` header either.

**Comment by woutslakhorst** [comment]
Sounds logical, let's be done with it then
