### ISSUE TITLE
Add TLS trusted certificate event

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-registry#137]
Add an event that distributes a certificate across the network. This certificate is marked by a vendor as the certificate they want to use as client certificate in FHIR data connections.

Other nodes will only accept the certificate if the CA is trusted. All Node CA's are trusted by default.

For local/development purposes this allows a node to publish their mTLS certificate which is also used for the registry connection.

- [ ] Add event format (#138)
- [ ] Add event processing (PR ref here)
- [ ] Add CMD for registering event from CLI (PR ref here)

**Comment by woutslakhorst** [comment]
This feature will help automate secure connection management for reverse proxies. It's not required for dev/workshops

**Comment by reinkrul** [comment]
> Other nodes will only accept the certificate if the CA is trusted.

Does that mean we don't include the CA tree in the event? If we do, the certificate would always be trusted.

**Comment by woutslakhorst** [comment]
uncertain at this point in time

**Comment by woutslakhorst** [comment]
Current RFC's no longer require this feature
