### ISSUE TITLE
Add 'identity' parameter

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-registry#43]
This parameter will hold the identity of the entity running the Nuts node. For now, it will only accept vendors (specified by URN-encoded OID). In future we can extend this to other entity types.

When starting the Nuts node, the registry will perform a sanity check:
1. is the vendor registered (in the registry)?
2. is the key material present (in the crypto module)?

If it fails, it warn the administrator (message in server log) and instruct what to do next.

We previously discussed the possibility to derive this identity from the private keys (+ certs) present in the crypto module. However, this can pose a problem when there are keys/certificates of multiple Nuts nodes in the crypto module, either by accident or when the (future) Vault backend is shared by multiple nodes. Therefore I feel it's safer to have explicitly configure the node identity.

In the auth module there's a parameter 'actingPartyCN', but this could then be looked up in the registry.

**Comment by woutslakhorst** [comment]
The same as Corda does in the node.conf file
