### ISSUE TITLE
Remove attribute Endpoint.ID

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-registry#48]
Endpoint.ID is only used in Corda endpoints for the X500 name. We don't need an attribute uniquely identifying an endpoint (other than the event hash).

Remove Endpoint.ID by first deprecating it and copying it to the property bag, when it concerns a Corda endpoint. Remove it in the version after that.

**Comment by reinkrul** [comment]
We might need the ID to distinguish endpoints: #87

**Comment by woutslakhorst** [comment]
I also commented there: (type, url, version) should be unique in time.

**Comment by reinkrul** [comment]
Not required by nextgen.
