### ISSUE TITLE
There is no way of distinguishing two endpoints for the same care provider and type

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-registry#87]
When a care provider has multiple endpoints of the same type, like an sso for two of its software packages, it is currently not possible to distinguish the two. This provides problems for the rendering of buttons.
We might introduce a HumanName, or make it easier to trace back to the vendor.

Use-case: select the endpoint for this agb of this type. When more endpoints are returned, there is no way of distinguishing between the endpoints. Usually an SSO has the name of the system on it, like "Vip-live" or "ozo". So the vendor identifier might be a valid filter option.

Another option would be pinpointing the endpoint by identifier. A requirement would be that this identifier does not change when the record gets updated.

**Comment by JoeriLandman** [comment]
The HumanName alone might not be enough. This might break when organisations start calling the HumanName 'SSO' etc.

The same goes for the vendor. When a organisation is running 2 software systems of 1 vendor with both nuts SSO receive functionality.

**Comment by woutslakhorst** [comment]
something for the parametersMap?

**Comment by reinkrul** [comment]
I don't think we should add another identifier to endpoints. We already have 'ID' which can be used to (technically) distinguish endpoints. An end user having to distinguish endpoints is a bolt-specific problem and I agree with @woutslakhorst that the property bag should be used for that purpose.

Endpoints IDs don't change when endpoints are updated (since you update an endpoint by specifying new data for an existing ID).

**Comment by woutslakhorst** [comment]
you probably want (type, url, version) to be unique in a moment in time (using periods) for a given org-endpoint combo.

**Comment by reinkrul** [comment]
In Nextgen endpoints are bound using a 'service' which can contain the Bolt name. If there's more need to disambiguate endpoints from different vendors for the same org/service I'd say the vendor name could be shown or alias-ed by the implementation (so it can show the vendor's product name for example, which might make more sense to the end user).
